export const acts = {
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USER: 'FETCH_USER',
  SET_SELECTED_PAGE: 'SET_SELECTED_PAGE',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  START_LOADING_USER_PROFILE: 'START_LOADING_USER_PROFILE',
  END_LOADING_USER_PROFILE: 'END_LOADING_USER_PROFILE',
};
